# analyzer rules
analyzer_rules:
    - unused_import

# rule identifiers to exclude from running
disabled_rules:
    - line_length
    - todo
    - trailing_whitespace
    - function_body_length
    - cyclomatic_complexity
    - nesting
    - large_tuple
    - function_parameter_count
    - private_over_fileprivate
    - empty_count
    - multiline_function_chains
    - empty_enum_arguments
    - type_name
    - vertical_whitespace_opening_braces
    
    # Code style
opt_in_rules:
    - unused_optional_binding
    - identifier_name
    - array_init
    - unneeded_parentheses_in_closure_argument
    - closure_end_indentation
    - closure_spacing
    - collection_alignment
    - colon
    - convenience_type
    - discouraged_object_literal
    - empty_collection_literal
    - empty_string
    - fatal_error_message
    - first_where
    - force_unwrapping
    - last_where
    - legacy_random
    - literal_expression_end_indentation
    - multiline_parameters
    - operator_usage_whitespace
    - overridden_super_call
    # - pattern_matching_keywords case let .foo(someting) zamiast case .foo(let something)
    - prefer_self_type_over_type_of_self
    - redundant_nil_coalescing
    - redundant_type_annotation
    - toggle_bool
    - vertical_whitespace_closing_braces
    - yoda_condition
    
# paths to include during linting. `--path` is ignored if present.
included:
- ReactiveCalendar
# paths to ignore during linting. Takes precedence over `included`.
excluded:
    - Carthage
    - Pods
    - SnapKit
type_body_length:
    - 300
    - 400
file_length:
    - 500
    - 600
force_cast:
    severity: warning
force_try:
    severity: warning
force_unwrapping:
    severity: warning
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle)
